name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup
        uses: actions-rs/toolchain@master
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          default: true
          override: true

      - name: Install
        uses: actions-rs/install@master
        with:
          crate: wasm-bindgen-cli
          version: latest
          use-tool-cache: true

      - name: Build
        run: cargo build --release --target wasm32-unknown-unknown && wasm-bindgen ./target/wasm32-unknown-unknown/release/counter-iced-sample.wasm --out-dir public --web

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
